services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: 'listen --forward-to host.docker.internal:5000/webhooks'
    env_file:
      - docker.env

  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=greenscape-dev

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  postgres-data:
    driver: local
