services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=greenscape-dev

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  postgres-data:
    driver: local
